### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by rainer2208** [allusive-dev/buttery-picom#1]
Hi, I would like to check out your  picom configuration, but I am unable to locate the package.  

I have tried yay picom-pijulius-git and pacman -S picom-pijulius-git, and tried to find it on the AUR website, but no succsess. 

Any hints? I am on Arch linux

**Comment by allusive-dev** [comment]
Hey. I have taken a peek and it looks like pijulius picom has been taken off the aur.
No idea why. 
Here is the link to the github repository where it gives instruction on how you can build it without the aur package.
https://github.com/pijulius/picom
I will do some more research and see if i can find out why the package was taken down and see if i can get it back up.

**Comment by rainer2208** [comment]
Hi, thanks for the reply. I hope you can get the repo back online soon. In the meantime, I will check out the build version.

**Comment by allusive-dev** [comment]
Hello @rainer2208 
Awesome news!
After ages of learning how to publish a package to the AUR, I have successfully republished the package under `picom-allusive`
https://aur.archlinux.org/packages/picom-allusive
